FROM node:22-alpine

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY pnpm-lock.yaml  ./
RUN pnpm fetch

COPY package.json pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile 

COPY . .

COPY entrypoint.sh ./
RUN chmod +x entrypoint.sh

EXPOSE 5000

CMD ["./entrypoint.sh"]